config/routes.rb
Rails.application.routes.draw do
  resources :places do
    resources :posts
  end

  root to: 'places#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/place.rb
class Place < ApplicationRecord
  # talks to the "places" table
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  # talks to the "posts" table
  belongs_to :place
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  # Controller actions go here
  class PlacesController < ApplicationController
    def index
      @places = Place.all
    end
  
    def show
      @place = Place.find(params[:id])
    end
  
    def new
      @place = Place.new
    end
  
    def create
      @place = Place.new(place_params)
  
      if @place.save
        redirect_to @place
      else
        render :new
      end
    end
  
    private
  
    def place_params
      params.require(:place).permit(:name)
    end
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # Controller actions go here
  class PostsController < ApplicationController
    before_action :set_place
  
    def new
      @post = @place.posts.new
    end
  
    def create
      @post = @place.posts.new(post_params)
  
      if @post.save
        redirect_to @place
      else
        render :new
      end
    end
  
    private
  
    def set_place
      @place = Place.find(params[:place_id])
    end
  
    def post_params
      params.require(:post).permit(:title, :description, :date)
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StarterApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/places/index.html.erb
<h1>Places</h1>

<%= link_to 'New Place', new_place_path %>

<ul>
  <% @places.each do |place| %>
    <li>
      <%= link_to place.name, place_path(place) %>
    </li>
  <% end %>
</ul>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= form_with(model: @place, local: true) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.submit %>
<% end %>

app/views/places/show.html.erb
<h1><%= @place.name %></h1>

<%= link_to 'New Post', new_place_post_path(@place) %>

<ul>
  <% @place.posts.each do |post| %>
    <li>
      <h2><%= post.title %></h2>
      <p><%= post.description %></p>
      <p><%= post.date %></p>
    </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>New Post for <%= @place.name %></h1>

<%= form_with(model: [@place, @post], local: true) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :description %>
  <%= form.text_area :description %>

  <%= form.label :date %>
  <%= form.date_field :date %>

  <%= form.submit %>
<% end %>